version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "next"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/capri"
    target-branch: "next"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/create"
    target-branch: "next"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/preact"
    target-branch: "next"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/react"
    target-branch: "next"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/react-render-to-string"
    target-branch: "next"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/solid"
    target-branch: "next"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/svelte"
    target-branch: "next"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/preact"
    target-branch: "next"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/react"
    target-branch: "next"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/solid"
    target-branch: "next"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/svelte"
    target-branch: "next"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
