name: CI

on:
  workflow_dispatch:
  push:
    branches: [main, next]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm test
      - run: npm run examples
      - run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: deploy examples
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: .github/pages
          clean: true
